import { useOutletContext } from 'react-router-dom';
import { Badge } from '../components/ui';
import { dateTime, money, shiftLabel, statusTone } from '../lib/format';
import { initials } from '../data/content';

export default function FamilyOverview() {
  const detail = useOutletContext();
  const { enrollment, events = [], installments = [], documents = [] } = detail;
  const facts = [['Turma atual', enrollment.from_class_name || '—'], ['Próxima turma', `${enrollment.target_grade_name} · ${shiftLabel(enrollment.target_shift)}`], ['Valor aplicável', money(enrollment.amount_cents)], ['Campanha', enrollment.campaign_name]];
  return <div className="grid grid--main"><div className="stack"><div className="card"><div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 18, flexWrap: 'wrap' }}><div style={{ display: 'flex', gap: 14 }}><div className="avatar avatar--lg">{initials(enrollment.guardian_name)}</div><div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}><h2 style={{ fontSize: 21, fontWeight: 800 }}>{enrollment.guardian_name}</h2><span className="meta">{enrollment.guardian_phone}</span></div></div><Badge tone={statusTone(enrollment.status)}>{enrollment.status_label}</Badge></div><div className="grid grid--4" style={{ marginTop: 20, paddingTop: 20, borderTop: '1px solid var(--line-3)' }}>{facts.map(([label, value]) => <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }} key={label}><span className="stat-label">{label}</span><strong style={{ fontSize: 14 }}>{value}</strong></div>)}</div></div><div className="card"><div className="card-title" style={{ marginBottom: 18 }}>Linha do tempo da jornada</div>{events.length ? events.map((event) => <div className="timeline-row" key={event.id}><div className="timeline-time">{dateTime(event.created_at)}</div><div className="timeline-rail"><i /><u /></div><div className="timeline-body"><div style={{ display: 'flex', alignItems: 'center', gap: 9, flexWrap: 'wrap' }}><h4>{event.title}</h4><span className="timeline-code">{event.code}</span></div><p>{event.body || 'Evento registrado no sistema.'}</p></div></div>) : <div className="notice">Nenhum evento registrado ainda.</div>}</div></div><div className="stack"><div className="card"><div className="card-title" style={{ marginBottom: 14 }}>Automação</div><div className="grid grid--2"><div><span className="stat-label">Tentativas</span><strong>{enrollment.attempts} de {enrollment.max_attempts}</strong></div><div><span className="stat-label">Próxima ação</span><strong>{enrollment.next_action || dateTime(enrollment.next_action_at)}</strong></div></div><div className="notice notice--soft" style={{ marginTop: 14 }}>Ações operacionais de envio dependem da integração WhatsApp, que ainda não possui Edge Function configurada.</div></div><div className="card"><div className="card-title" style={{ marginBottom: 14 }}>Assinatura e pagamento</div>{[...documents.map((item) => ({ label: item.document_versions?.documents?.title || 'Documento', sub: item.status })), ...installments.map((item) => ({ label: `Parcela ${item.number}`, sub: `${money(item.amount_cents)} · ${item.status}` }))].map((item, index) => <div className="row-item" style={{ background: 'var(--surface)', borderColor: 'var(--line-2)' }} key={`${item.label}-${index}`}><div className="who"><strong>{item.label}</strong><span>{item.sub}</span></div></div>)}</div></div></div>;
}
